spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: [password]
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka